import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <ul>
          <li><Link href='/'>main</Link></li>
          <li><Link href='/about'>about</Link></li>
          <li><Link href='/gallery'>gallery</Link></li>
        </ul>
      </nav>
      <main>
        <section>1</section>
        <section>2</section>
      </main>
    </>
  )
}
